# Reference: http://www.appveyor.com/docs/appveyor-yml
# Notes:
#   - Indent each level of configuration with 2 spaces. Do not use tabs!

#---------------------------------#
#      general configuration      #
#---------------------------------#

version: $(smallversion).{build}

# Do not build on tags (GitHub and BitBucket)
skip_tags: true
#Do not build if we change any of this files
skip_commits:
  files:
    - '**/*.md'
    - '**/*.editorconfig'
image: Visual Studio 2019

#---------------------------------#
#    environment configuration    #
#---------------------------------#

environment:
  smallversion: 1.0
cache:
  - packages -> **\packages.config
  - Libs\model\patch_experts\
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(configuration)'

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration:
 - Debug
 - Release
platform: x64
build:
  parallel: true
  verbosity: minimal
  publish_nuget: true
before_build:
  - nuget restore
  - ps: '& "$env:appveyor_build_folder\download_models.ps1"'
after_build:
#ClientUpdater post build commands
 - ps: mkdir "$env:appveyor_build_folder\FinalFiles\$env:configuration\GazeTracker"
 - ps: xcopy /s/y "$env:appveyor_build_folder\GazeTracker\bin\$env:platform\$env:configuration\*.*" "$env:appveyor_build_folder\FinalFiles\$env:configuration\GazeTracker"
 #7zip everything
 - ps: 7z a "$env:appveyor_build_folder\GazeTracker-$env:configuration.zip" "$env:appveyor_build_folder\FinalFiles\$env:configuration\GazeTracker"
#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
 - path: .\GazeTracker-$(configuration).zip
   name: GazeTracker-$(configuration).zip
#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
 - provider: GitHub
   tag: $(appveyor_build_version)
   release: GazeTracker $(appveyor_build_version)
   description: 'Build $(appveyor_build_version)'
   artifact: GazeTracker-$(configuration).zip
   auth_token:
    secure: zWJqDvz3LjR2J358JIJKICwghW/DWRzs73KWb3KApTLOreA4c8DN1tos+O3qBMR7
   draft: false
   force_update: true
   on:
    branch: master